services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway
    ports:
      - "8607:8607"
    networks: # 关键：显式关联自定义网络
      - my-bridge  # 网络名称可自定义
networks:
  my-bridge:
    driver: bridge