services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway
    ports:
      - "8607:8607"
    networks:  # 关键：关联到外部网络
      - shared-net

networks:
  shared-net:  # 网络名称必须与手动创建的一致
    external: true  # 声明使用外部网络