CREATE TABLE `admin` (
                         `uid` varchar(32) NOT NULL COMMENT '唯一uid',
                         `user_name` varchar(60) NOT NULL COMMENT '用户名',
                         `pass_word` varchar(60) NOT NULL COMMENT '密码',
                         `gender` varchar(1) DEFAULT NULL COMMENT '性别(1:男2:女)',
                         `avatar` varchar(100) DEFAULT NULL COMMENT '个人头像',
                         `email` varchar(60) DEFAULT NULL COMMENT '邮箱',
                         `birthday` date DEFAULT NULL COMMENT '出生年月日',
                         `mobile` varchar(11) DEFAULT NULL COMMENT '手机',
                         `valid_code` varchar(50) DEFAULT NULL COMMENT '邮箱验证码',
                         `summary` varchar(200) DEFAULT NULL COMMENT '自我简介最多200字',
                         `login_count` int(11) unsigned DEFAULT '0' COMMENT '登录次数',
                         `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
                         `last_login_ip` varchar(50) DEFAULT '127.0.0.1' COMMENT '最后登录IP',
                         `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态',
                         `create_time` datetime NOT NULL COMMENT '创建时间',
                         `update_time` datetime NOT NULL COMMENT '更新时间',
                         `nick_name` varchar(60) DEFAULT NULL COMMENT '昵称',
                         `qq_number` varchar(20) DEFAULT NULL COMMENT 'QQ号',
                         `we_chat` varchar(20) DEFAULT NULL COMMENT '微信号',
                         `occupation` varchar(60) DEFAULT NULL COMMENT '职业',
                         `github` varchar(60) DEFAULT NULL COMMENT 'github地址',
                         `gitee` varchar(60) DEFAULT NULL COMMENT 'gitee地址',
                         `role_uid` varchar(32) DEFAULT NULL COMMENT '拥有的角色uid',
                         `person_resume` text COMMENT '履历',
                         PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理员表';