CREATE TABLE `user` (
                          `uid` varchar(32) NOT NULL COMMENT '唯一uid',
                          `user_name` varchar(255) NOT NULL COMMENT '用户名',
                          `pass_word` varchar(32) NOT NULL COMMENT '密码',
                          `gender` tinyint(1) unsigned DEFAULT NULL COMMENT '性别(1:男2:女)',
                          `avatar` varchar(100) DEFAULT NULL COMMENT '个人头像',
                          `email` varchar(60) DEFAULT NULL COMMENT '邮箱',
                          `birthday` date DEFAULT NULL COMMENT '出生年月日',
                          `mobile` varchar(50) DEFAULT NULL COMMENT '手机',
                          `valid_code` varchar(255) DEFAULT NULL COMMENT '邮箱验证码',
                          `summary` varchar(200) DEFAULT NULL COMMENT '自我简介最多150字',
                          `login_count` int(11) unsigned DEFAULT '0' COMMENT '登录次数',
                          `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
                          `last_login_ip` varchar(50) DEFAULT '127.0.0.1' COMMENT '最后登录IP',
                          `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态',
                          `create_time` datetime NOT NULL COMMENT '创建时间',
                          `update_time` datetime NOT NULL COMMENT '更新时间',
                          `nick_name` varchar(255) DEFAULT NULL COMMENT '昵称',
                          `source` varchar(255) DEFAULT NULL COMMENT '资料来源',
                          `uuid` varchar(255) DEFAULT NULL COMMENT '平台uuid',
                          `qq_number` varchar(20) DEFAULT NULL COMMENT 'QQ号',
                          `we_chat` varchar(255) DEFAULT NULL COMMENT '微信号',
                          `occupation` varchar(255) DEFAULT NULL COMMENT '职业',
                          `comment_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '评论状态 1:正常 0:禁言',
                          `ip_source` varchar(255) DEFAULT NULL COMMENT 'ip来源',
                          `browser` varchar(255) DEFAULT NULL COMMENT '浏览器',
                          `os` varchar(255) DEFAULT NULL COMMENT '操作系统',
                          `start_email_notification` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启邮件通知 1:开启 0:关闭',
                          `user_tag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '用户标签：0：普通用户，1：管理员，2：博主 等',
                          `loading_valid` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否通过加载校验【0 未通过，1 已通过】',
                          PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';