CREATE TABLE `blog` (
                        `uid` varchar(32) NOT NULL COMMENT '唯一uid',
                        `title` varchar(200) DEFAULT NULL COMMENT '博客标题',
                        `summary` varchar(255) DEFAULT NULL COMMENT '博客简介',
                        `content` longtext COMMENT '博客内容',
                        `tag_uid` varchar(255) DEFAULT NULL COMMENT '标签uid',
                        `click_count` int(11) DEFAULT '0' COMMENT '博客点击数',
                        `collect_count` int(11) DEFAULT '0' COMMENT '博客收藏数',
                        `file_uid` varchar(255) DEFAULT NULL COMMENT '标题图片uid',
                        `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态',
                        `create_time` datetime NOT NULL  COMMENT '创建时间',
                        `update_time` datetime NOT NULL  COMMENT '更新时间',
                        `admin_uid` varchar(32) DEFAULT NULL COMMENT '管理员uid',
                        `is_original` varchar(1) DEFAULT '1' COMMENT '是否原创（0:不是 1：是）',
                        `author` varchar(255) DEFAULT NULL COMMENT '作者',
                        `articles_part` varchar(255) DEFAULT NULL COMMENT '文章出处',
                        `blog_sort_uid` varchar(32) DEFAULT NULL COMMENT '博客分类UID',
                        `level` tinyint(1) DEFAULT '0' COMMENT '推荐等级(0:正常)',
                        `is_publish` varchar(1) DEFAULT '1' COMMENT '是否发布：0：否，1：是',
                        `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序字段',
                        `open_comment` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启评论(0:否 1:是)',
                        `type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '类型【0 博客， 1：推广】',
                        `outside_link` varchar(1024) DEFAULT NULL COMMENT '外链【如果是推广，那么将跳转到外链】',
                        `oid` int(11) NOT NULL AUTO_INCREMENT COMMENT '唯一oid',
                        `user_uid` varchar(32) DEFAULT NULL COMMENT '投稿用户UID',
                        `article_source` tinyint(1) NOT NULL DEFAULT '0' COMMENT '文章来源【0 后台添加，1 用户投稿】',
                        PRIMARY KEY (`uid`,`oid`),
                        KEY `oid` (`oid`)
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8 COMMENT='博客表';