services:
  picture:
    build:
      context: .
      dockerfile: Dockerfile
    image: picture
    container_name: picture
    ports:
      - "8602:8602"
    networks:  # 关键：关联到外部网络
      - shared-net

networks:
  shared-net:  # 网络名称必须与手动创建的一致
    external: true  # 声明使用外部网络