version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin
    container_name: admin
    ports:
      - "8085:8085"
    networks: # 关键：显式关联自定义网络
      - my-bridge  # 网络名称可自定义
networks:
  my-bridge:
    driver: bridge