version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin
    container_name: admin
    ports:
      - "8085:8085"
    networks:  # 关键：关联到外部网络
      - shared-net

networks:
  shared-net:  # 网络名称必须与手动创建的一致
    external: true  # 声明使用外部网络