version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin
    container_name: admin
    ports:
      - "8085:8085"
networks:
  my_network:
    driver: bridge