server:
  port: 8607

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.64.138:8848
      config:
        server-addr: 124.222.64.138:8848
        file-extension: yaml
        group: dev