server:
  port: 8605
spring:
  application:
    name: search
  jmx:
    default-domain: search
  security:
    user:
      name: ykr
      password: admin998
  data:
    # elasticsearch:
    #   cluster-name: elasticsearch
    #   cluster-nodes: localhost:9300
    solr:
      host: http://localhost:8080/solr
      core: collection1
      repositories:
        enabled: true

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8606
        username: ykr
        password: admin998
      instance:
        service-base-url: http://localhost:8605

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://localhost:9411  # 指定了Zipkin服务器的地址

  #nacos相关配置
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.64.138:8848

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always